name = "probaterealestatesales"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = ".next"

[env.production]
name = "probaterealestatesales"

[env.preview]
name = "probaterealestatesales-preview"

# Image optimization settings
[env.production.vars]
NEXT_IMAGE_DOMAINS = "images.unsplash.com,via.placeholder.com"

# Environment variables
[env.production.vars]
NODE_ENV = "production"
